# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - https://link.hhtjim.com/163/1409311773.mp3
    - https://link.hhtjim.com/163/1417265541.mp3
    - https://link.hhtjim.com/163/2064261972.mp3
    - https://link.hhtjim.com/163/1428153831.mp3
    - https://link.hhtjim.com/163/1460606296.mp3
    - https://link.hhtjim.com/163/1371306566.mp3
    - https://link.hhtjim.com/163/28573320.mp3
    - https://link.hhtjim.com/163/441102354.mp3
    - https://link.hhtjim.com/163/441102355.mp3
    - https://link.hhtjim.com/163/441102356.mp3
    - https://link.hhtjim.com/163/441102358.mp3
    - https://link.hhtjim.com/163/441102359.mp3
    - https://link.hhtjim.com/163/441102360.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/img7.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/img1.jpg
  - /img/img2.jpg
  - /img/img3.jpg
  - /img/img4.jpg
  - /img/img5.jpg
  - /img/img6.jpg
  - /img/img7.jpg
  - /img/img8 (1).JPG
  - /img/img8 (2).JPG
  - /img/img8 (3).JPG
  - /img/img8 (4).JPG
  - /img/img8 (5).JPG
  - /img/img8 (6).JPG
  - /img/img8 (7).JPG
  - /img/img8 (8).JPG
  - /img/img8 (9).JPG
  - /img/img8 (10).JPG
  - /img/img8 (11).JPG
  - /img/img8 (12).JPG
  - /img/img8 (13).JPG
  - /img/img8 (14).JPG
  - /img/img8 (15).JPG
  - /img/img8 (16).JPG
  - /img/img8 (17).JPG
  - /img/img8 (18).JPG
  - /img/img8 (19).JPG
  - /img/img8 (20).JPG
  - /img/img8 (22).JPG
  - /img/img8 (23).JPG
  - /img/img8 (24).JPG
  - /img/img8 (25).JPG
  - /img/img8 (26).JPG
  - /img/img8 (27).JPG
  - /img/img8 (28).JPG
  - /img/img8 (29).JPG

# 是否使用mathjax
mathjax: true


# 是否关闭默认滚动条
scrollbar: false

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: false

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    github: https://www.github.com/Xchkoo
    email: mailto:Xchkoo@foxmail.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: true
    # 备案号
    beianInfo: 
    - © Copyright 2021 Xchkoo All rights reserved.
    # 链接地址
    link: https://github.com/Xchkoo

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '7a61432ab10a4ea8f35f'
    # 应用秘钥
    clientSecret: 'b2913eac810df502dde1418253f24e86badb4c79'
    # issue仓库名
    repo: 'BlogComments'
    # Github名
    owner: 'Xchkoo'
    # Github名
    admin: ['Xchkoo']
    # Ensure uniqueness and length less than 50
    id: location.href
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: 
  - Xchkoo
  - Xchkoo.top
  - blog

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/X.png

# rss文件
rss: atom.xml


#how to create a new post:
#---
#title: My awesome title
#date: 2016-10-12 18:38:45
#categories: 
#    - 分类1
#    - 分类2
#tags: 
#    - 标签1
#    - 标签2
#mp3: http://domain.com/awesome.mp3
#cover: http://domain.com/awesome.jpg
#---

